# Generated by Django 4.1.7 on 2023-05-10 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=40)),
                ('accno', models.CharField(max_length=15)),
                ('number', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=30)),
                ('pin', models.CharField(max_length=6)),
                ('dob', models.CharField(max_length=10)),
                ('typeac', models.CharField(max_length=10)),
                ('accbal', models.CharField(max_length=8, null=True)),
            ],
            options={
                'db_table': 'Accholders',
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('phonenumber', models.IntegerField()),
                ('password', models.CharField(max_length=20)),
                ('branch', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'Registration',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=20)),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal')], max_length=10)),
                ('current_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_datetime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Transactions',
            },
        ),
    ]
